### ISSUE TITLE
Error raised when using non-existent env vars for other OS

### ISSUE THREAD

**Issue by erikstantoncarlson** [blurstudio/hab-gui#24]
## Summary

In a hab distro or config json file, if a non-existent environment variable is set for an OS that is not the current one, hab gui will show a popup error window immediately after launch.
This happens specifically when using environment variable format syntax such as "{HOME!e}".

## Expected Behavior

No error should be raised since the environment variable was meant to be used for a different OS.

## Steps to Reproduce Behavior

1. Add a distro such as this one for Optical Flares:
```
{
    "name": "OpticalFlares13.2",
    "environment": {
        "os_specific": true,
        "*": {
            "set": {
                "OPTICAL_FLARES_LICENSE_SERVER_IP": "---.---.--.--"
            },
            "prepend": {
                "NUKE_PATH": "{relative_root}"
            }
        },
        "linux": {
            "set": {
                "OPTICAL_FLARES_PREFERENCE_PATH": "{HOME!e}"
            }
        },
        "windows": {
            "set": {
                "OPTICAL_FLARES_PREFERENCE_PATH": "{LOCALAPPDATA!e}"
            }
        }
    }
}
```
2. Add the distro to a config json.
3. Launch hab gui and it should error if the problematic config is chosen.

### Solution

Environment variables for OSs that are not the current one should probably be ignored.

## Environment

- Version: hab_gui 0.24.0, hab 0.42.0 
- OS and Python version: Windows 10, Python 3.9.12 

## Additional Context

This is the error copied from hab gui's popup exception window.
```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\hab_gui\widgets\distro_picker.py", line 65, in refresh
    cfg = resolver.resolve(uri)
  File "C:\Program Files\Python39\lib\site-packages\hab\resolver.py", line 335, in resolve
    return context.reduced(self, uri=uri)
  File "C:\Program Files\Python39\lib\site-packages\hab\parsers\hab_base.py", line 658, in reduced
    return FlatConfig(self, resolver, uri=uri)
  File "C:\Program Files\Python39\lib\site-packages\hab\parsers\flat_config.py", line 27, in __init__
    self._collect_values(self.original_node)
  File "C:\Program Files\Python39\lib\site-packages\hab\parsers\hab_base.py", line 95, in _collect_values
    if getattr(self, attrname) != NotSet:
  File "C:\Program Files\Python39\lib\site-packages\hab\parsers\flat_config.py", line 165, in environment
    self.merge_environment(version.environment_config, obj=version)
  File "C:\Program Files\Python39\lib\site-packages\hab\parsers\hab_base.py", line 616, in merge_environment
    merger.apply_platform_wildcards(
  File "C:\Program Files\Python39\lib\site-packages\hab\merge_dict.py", line 48, in apply_platform_wildcards
    self.update_platform(platform_data, data[platform], platform=platform)
  File "C:\Program Files\Python39\lib\site-packages\hab\merge_dict.py", line 146, in update_platform
    data[key] = self.formatter(value, platform=platform)
  File "C:\Program Files\Python39\lib\site-packages\hab\parsers\hab_base.py", line 498, in format_environment_value
    ret = Formatter(ext).format(value, **kwargs)
  File "C:\Program Files\Python39\lib\string.py", line 161, in format
    return self.vformat(format_string, args, kwargs)
  File "C:\Program Files\Python39\lib\site-packages\hab\formatter.py", line 111, in vformat
    ret = super().vformat(format_string, args, kwargs)
  File "C:\Program Files\Python39\lib\string.py", line 165, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "C:\Program Files\Python39\lib\string.py", line 205, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "C:\Program Files\Python39\lib\site-packages\hab\formatter.py", line 75, in get_field
    ret = super().get_field(field_name, args, kwargs)
  File "C:\Program Files\Python39\lib\string.py", line 270, in get_field
    obj = self.get_value(first, args, kwargs)
  File "C:\Program Files\Python39\lib\string.py", line 227, in get_value
    return kwargs[key]
KeyError: 'HOME'
```

I don't get this error in hab cli which is why I created this issue for hab gui.

**Comment by MHendricks** [comment]
This is a bug in hab and is fixed by https://github.com/blurstudio/hab/pull/106. This is released in `hab>=0.43.0`.
